



[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.8
exceptions = [
]

[licenses.private]
ignore = true
registries = [
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
]
deny = [
]
skip = [
]
skip-tree = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []

[output]
feature-depth = 1

[graph]
no-default-features = false
all-features = true
exclude = []
targets = [
    { triple = "wasm32-unknown-unknown" }
]
